# fly.toml app configuration file generated for paceline on 2026-05-06T06:11:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'paceline'
primary_region = 'ams'

[build]

[env]
  GRAPHHOPPER_URL = 'http://paceline-graphhopper.internal:8989'
  POCKETBASE_URL = 'http://paceline-pb.internal:8090'
  POCKETBASE_PUBLIC_URL = 'https://paceline-pb.fly.dev'
  POCKETBASE_ADMIN_EMAIL = 'dieter.goetelen@hotmail.com'
  POCKETBASE_ADMIN_PASSWORD = 'K6H3:AV_MW+7?&sc0Kjx'
  NEXT_PUBLIC_VAPID_PUBLIC_KEY=BBPpxaQiOHbUAqoD9C7Fxhp2e9l9B8JRaRiCFiMJ-gjjWIqae0A2jiWWRc_BG8cx_0K4SCRAr6qjs6hwHjfjaFI
  VAPID_PRIVATE_KEY=JmGbgefQ6Ec8TAkNFhPf-Wgnq8RMmGLHtUMTxGO55Ds
  VAPID_SUBJECT=mailto:admin@zoesh.app

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
