# fly.toml app configuration file generated for paceline on 2026-05-06T06:11:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'paceline'
primary_region = 'ams'

[build]

[env]
  GRAPHHOPPER_URL = 'http://vnext-graphhopper.internal:8989'
  POCKETBASE_URL = 'http://vnext-pocketbase.internal:8090'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
